name: intel_dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - plotly
  - dash
  - dash-bootstrap-components
  - flask
  - ipykernel
  - jupyterlab
  - dash-core-components
